CREATE DATABASE mealbuddy;
\c mealbuddy;

CREATE TABLE recipes (
   id INT GENERATED ALWAYS AS IDENTITY,
   name TEXT NOT NULL,
   PRIMARY KEY (id)
);

CREATE TABLE ingredients (
   ingredients_id INT GENERATED ALWAYS AS IDENTITY,
   ingredients TEXT[] NOT NULL,
   recipe_id INT,
   PRIMARY KEY (ingredients_id),
   CONSTRAINT fk_recipe
   FOREIGN KEY (recipe_id)
   REFERENCES recipes(id)
   ON DELETE CASCADE
);

CREATE TABLE instructions (
   instruction_id INT GENERATED ALWAYS AS IDENTITY,
   instructions TEXT[] NOT NULL,
   recipe_id INT,
   PRIMARY KEY (instruction_id),
   CONSTRAINT fk_recipe
   FOREIGN KEY (recipe_id)
   REFERENCES recipes(id)
   ON DELETE CASCADE
);

INSERT INTO recipes (name) VALUES ('Thai Peanut Chicken');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"1 1/2 lbs of boneless skinless chicken thighs or breast", "3-4 tablespoons Thai Red Curry Paste", "2 tablespoons ground ginger", "3 tablespoons sesame oil or extra virgin olive oil", "1/4 cup fresh Thai basil or regular basil chopped", "1/4 cup fresh cilantro, chopped, plus more for serving", "1 (14 ounce) can full fat coconut milk", "1/4 cup low sodium soy sauce", "2 tablespoons fish sauce", "1/2 cup creamy peanut butter", "juice of 1 lime", "steamed rice, for serving", "roasted peanuts and Persian cucumbers, for serving"}', 1);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"Toss the chicken with the 2 tablespoons Thai red curry paste, the ginger, and 1 tablespoon oil. Let sit 5 minutes.", "Heat 2 tablespoons oil in a large Dutch oven or pot over medium-high heat. Add the chicken and sear on both sides until browned, about 2 minutes. Add the remaining Thai red curry paste, the basil, and the cilantro.", "Reduce the heat to low. Add the coconut milk, soy sauce, fish sauce (if using), and 1/4 cup water. Partially cover and simmer for 20-30 minutes, or until the chicken is cooked through. Stir in the peanut butter and lime juice. Simmer until thickened, about 5 minutes. Note, there is going to be a lot of sauce.", "To make the spicy lime mango. Combine all ingredients in a bowl.", "Serve the chicken and sauce over rice. Top with roasted peanuts, cucumbers, and spicy lime mango."}', 1);

INSERT INTO recipes (name) VALUES ('Penne alla Vodka');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"16 ounces penne pasta", "2 tablespoons butter", "2 teaspoons garlic", "1/2 teaspoon crushed red pepper flakes plus more for garnish if desired", "28 ounce can Italian style or San Marzano whole tomatoes", "1/4 cup vodka", "1 cup heavy cream", "3/4 cup grated parmesan cheese plus more for serving", "salt and pepper to taste", "2 tablespoons chopped parsley"}', 2);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"Cook the pasta in salted boiling water according to package directions.", "While the pasta is cooking, prepare the sauce.", "Melt the butter in a large pan over medium heat. Add the garlic and red pepper flakes and cook for 30 seconds.", "Place the tomatoes in a blender or food processor and puree until smooth. Pour the tomato puree into the pan.", "Add the vodka to the pan. Simmer the sauce for 10 minutes over medium low heat.", "Stir in the heavy cream and parmesan cheese and simmer for another 5 minutes or until thickened. Season the sauce with salt and pepper to taste.", "Pour the sauce over the pasta and toss to coat. Sprinkle with parsley, parmesan cheese and red pepper flakes (optional), then serve."}', 2);

INSERT INTO recipes (name) VALUES ('Jalapeño Basil Chicken Stir Fry');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"1 1/2 pounds boneless skinless chicken thighs or breasts, thinly sliced", "1 tablespoon cornstarch", "1 teaspoon ground turmeric", "1 teaspoon ground ginger", "1-2 teaspoons black pepper", "3 tablespoons sesame oil or extra virgin olive oil", "1/3 cup low sodium soy sauce", "1/4 cup honey", "2 tablespoons rice vinegar", "1 tablespoon fish sauce (optional)", "2 bell peppers, sliced", "1-2 jalapeños, seeded, if desired, and sliced", "1 medium shallot, sliced", "1 cup fresh Thai or regular basil chopped"}', 3);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"In a medium bowl, toss together the chicken, cornstarch, turmeric, ginger, and black pepper.", "In a glass jar, combine the honey, soy sauce, rice vinegar, fish sauce (if using) and 1/4 cup water.", "Heat the oil in a large skillet over medium-high heat. Add the bell peppers, jalapeños, and shallots, cook 2-3 minutes, until the peppers are charring. Stir in the chicken, tossing to combine with the peppers, cook 2 minutes.", "Pour in the honey/soy sauce mix. Bring the sauce to a boil over medium-high heat and cook until the sauce coats the chicken, about 8-10 minutes. Remove from the heat and stir in the basil.", "Serve the chicken and sauce over bowls of coconut lemongrass rice (recipe in notes). Top with plenty of fresh basil."}', 3);

INSERT INTO recipes (name) VALUES ('Thai Peanut Chicken Ramen');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"4 cups low sodium chicken broth", "1 can (14 ounce) coconut milk", "1/4 cup low sodium soy sauce", "2 tablespoons fish sauce", "2 tablespoons honey", "1/3 cup creamy peanut butter", "1/4 cup Thai red curry paste", "3/4 pound boneless, skinless chicken breasts", "8 ounces cremini mushrooms, sliced", "2 red bell peppers, chopped", "1 inch fresh ginger, grated", "1 clove garlic, minced or grated", "2-4 squares ramen noodles", "juice of 1 lime", "3 cups fresh baby spinach", "1/3 cup fresh basil or cilantro, roughly chopped, plus more for serving", "chopped peanuts and toasted sesame oil, for serving"}', 4);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"In a large soup pot, combine the chicken broth, coconut milk, soy sauce, fish sauce, honey, peanut butter, and curry paste. Add the chicken, cremini mushrooms, red peppers, ginger, and garlic. Set over medium heat on the stove and bring to a simmer, reduce the heat to medium-low and simmer 15 minutes or until the chicken is cooked through and shreds easily.", "Once done cooking, shred the chicken.", "Bring the soup to a boil over high heat. Stir in the noodles, lime juice, spinach, and cilantro. Let sit 5 minutes or until the noodles are soft.", "Ladle the soup into bowls and top with peanuts and toasted sesame oil. Enjoy!"}', 4);

INSERT INTO recipes (name) VALUES ('Creamy Cajun Chicken Pasta');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"1 pound short-cut pasta", "4 tablespoons extra virgin olive oil", "1 pound chicken tenders, cut into bite size pieces", "1 tablespoon, plus 1-2 teaspoons cajun seasoning", "kosher salt and black pepper", "1 medium yellow onion, chopped", "2 bell peppers, chopped", "3 cloves garlic, finely chopped or grated", "crushed red pepper flakes", "1 cup low sodium chicken broth", "1 cup milk", "2 ounces cream cheese, at room temperature", "1/2 cup grated parmesan cheese", "2 tablespoons chopped fresh basil"}', 5);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"Bring a large pot of salted water to a boil. Cook the pasta al dente, according to package directions. Drain.", "In the same pot set over medium-high heat, add 2 tablespoons olive oil, the onion, chicken, and 1 tablespoon cajun seasoning. Cook until browned all over, about 5 minutes. Spoon the chicken onto a plate.", "To the pot, add 2 tablespoons olive oil, the bell peppers, and garlic. Cook another 5 minutes until the peppers are soft. Stir in 1-2 teaspoons cajun seasoning. Add a pinch each of red pepper flakes, salt, and pepper. Cook another minute, until the spices are fragrant, then pour in the broth and milk. Add the cream cheese. Whisk until smooth. Bring the sauce to a gentle simmer and cook 5 minutes, until thickened slightly.", "Stir in the parmesan. Then toss in the pasta and chicken and cook 2-3 minutes. Remove from the heat and stir in the basil. Serve immediately topped with additional basil. Enjoy!"}', 5);

INSERT INTO recipes (name) VALUES ('Zuppa Toscana');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"1 pound bulk mild Italian sausage", "1 1/4 teaspoons crushed red pepper flakes", "4 slices bacon, cut into 1/2 inch pieces", "1 large onion, diced", "1 tablespoon minced garlic", "5 (13.75 ounce) cans chicken broth", "6 medium potatoes, thinly sliced", "1 cup heavy cream", "1/4 bunch fresh spinach, tough stems removed"}', 6);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"Cook Italian sausage and red pepper flakes in a Dutch oven over medium-high heat until crumbly, browned, and no longer pink, 10 to 15 minutes. Drain and set aside.", "Cook bacon in the same Dutch oven over medium heat until crisp, about 10 minutes. Drain, leaving a few tablespoons of drippings with the bacon in the bottom of the Dutch oven. Stir in onions and garlic; cook until onions are soft and translucent, about 5 minutes.", "Stir in chicken broth and bring to a boil over high heat. Add potatoes and simmer until fork tender, about 20 minutes. Reduce heat to medium; stir in cream, cooked sausage, and spinach. Cook and stir until spinach has wilted and sausage is warmed through; serve."}', 6);

INSERT INTO recipes (name) VALUES ('Sopa de Albondigas (Chicken Meatball Soup)');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"8 tomatoes", "Medium onion", "Garlic", "Vegetable oil", "Chicken broth", "Cut coriander", "Salt", "Ground Chicken", "Sandwich bread", "Milk", "Smoothie egg", "Chopped garlic tooth", "Whole black peppers", "Salt"}', 7);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"Place the tomatoes, onion, and garlic in a comal to roast. While they are roasting make sure to turn them so that they are roasting evenly. Garlic will take less time, so remove it as soon as it is roasted, if you let it burn it will taste bitter. This step takes about 5-7 minutes. Once the tomatoes, onion and garlic are roasted, place them in the blender and grind them until a very fine sauce forms. If your tomatoes are not juicy and the blender does not grind them well, add 1/4 cup of water.", "Heat the oil in a pot at medium high temperature. Once the oil is hot, empty the sauce very carefully since the oil is hot it can jump, cook for 5 minutes and add the chicken stock. Keep cooking. When it starts to boil, reduce the flame to a very low boil. While the tomato sauce is cooking we will prepare the meatballs.", "To prepare the meatballs, in a small bowl, put the bread slices with the milk to which the bread is softened. This took about a minute. Place the meat in a large bowl and make a hole in the middle.", "In the molcajete grind the pepper and the garlic, well ground, you add 2 tablespoons of water to which a pastite forms. You add this to the meat as well as the beaten egg, bread, and milk. You can use garlic powder and ground pepper if you want but the taste when you grind it fresh is unmatched.", "With great care, and without kneading, with the hands or with a wooden spoon we are going to mix the meat. Do not mix it too much because then the meatballs will be hard. To form the meatballs, take small portions and shape it with the palms of your hand. About the size of a golf ball. Carefully place each ball in the tomato broth that is boiling.", "Keep doing the rest of the meatballs. Once all the meatballs are in the broth, cook for about 15 to 20 more minutes. A few minutes before they finish cooking, add the finely cut coriander and season with salt.", "This soup is traditionally served with rice, either white or beans."}', 7);

INSERT INTO recipes (name) VALUES ('Sopa de Fideo (Mexican Noddle Soup)');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"1 tbsp. Oil (optional)", "8 oz. Angel hair pasta or whole wheat thin spaghetti, broken into 1 in. pieces", "1 can (14.5 oz) Diced tomatoes or 2 cups of fresh diced tomatoes", "1/2 Onion, white, chopped", "3 Garlic cloves, peeled", "10 cups Vegetable stock", "1 Mexican zucchini, diced", "1 Lime, cut into quarters"}', 8);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"In a medium pot get your vegetable stock boiling hot and set aside.", "Set a large pot to medium heat and add oil. Once the oil is hot add broken up noodles and toss to coat in oil. Continue to cook until noodles are golden brown, about 3 minutes.", "While the noodles are browning, place the tomatoes, onion, garlic, and 2 cups of the vegetable stock in the blender and process until smooth.", "Strain this mixture directly into the golden noodles still in the hot pot. Stir to prevent the noodles from sticking.", "Let mixture simmer for 1 minute. Add the rest of your stock and set heat to high. Add zucchini and cook noodles at a low boil until noodles are al dente and zucchini is tender. Stir often. Season.", "Serve with a wedge of lime so everyone can add as much lime juice as they like."}', 8);

INSERT INTO recipes (name) VALUES ('Lemon Pepper Cajun Chicken Fettucine Alfredo');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"1 pound linguine or fettuccini", "1 tablespoon extra virgin olive oil", "6 chicken cutlets or 1 pound tenders", "2 tablespoons cajun seasoning", "1 1/2 cups, plus 2 tablespoons parmesan cheese", "kosher salt and black pepper", "4 tablespoons salted butter", "3 cloves garlic, chopped", "crushed red pepper flakes", "2 tablespoons lemon juice", "1 cup low sodium chicken broth", "1 cup heavy cream", "2 tablespoons chopped fresh parsley"}', 9);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"Bring a large pot of salted water to a boil. Cook the pasta al dente, according to package directions. Drain.", "In bowl, toss together the olive oil, chicken, cajun seasoning, 2 tablespoons parmesan, and a big pinch of pepper.", "Melt 2 tablespoons butter in a large pan set over medium-high heat, add the chicken and sear until deeply golden on both sides, 5 minutes per side. Turn the heat off and pour over the lemon juice. Transfer to a plate.", "To the same pan, add 2 tablespoons butter, the garlic, and chili flakes. Cook 1 minute, until fragrant, then pour in the broth and milk. Whisk until smooth. Bring the sauce to a gentle simmer and cook 5 minutes, until slightly thickened. Stir in 1 1/2 cups parmesan, then toss in the pasta. Cook 2 minutes. Remove from the heat and stir in the parsley.", "Serve immediately topped with sliced chicken and parsley."}', 9);

INSERT INTO recipes (name) VALUES ('Simple Coconut Chicken Curry');
INSERT INTO ingredients (ingredients, recipe_id) VALUES ('{"2 tablespoons sesame oil", "2 pounds boneless skinless chicken breast, cubed", "2 tablespoons regular or spicy curry powder", "3-4 tablespoons red curry paste", "1 tablespoon tomato paste", "2 tablespoons salted butter", "2 garlic, chopped", "1 tablespoon chopped fresh ginger", "2 cups chopped broccoli florets", "2 1/2 cups canned coconut milk", "1/2 cup fresh chopped cilantro"}', 10);
INSERT INTO instructions (instructions, recipe_id) VALUES ('{"In a large skillet, combine the oil, chicken, curry powder, and a pinch of salt. Set over medium-high heat, then cook 3 minutes. Add the curry paste, tomato paste, butter, garlic, and ginger. Cook another 2 minutes.", "Add the broccoli, then pour in the coconut milk. Season with salt. Cook 5-10 minutes until the chicken is cooked through and the sauce has thickened.", "Stir in the cilantro. Serve the chicken and sauce over rice and with mango topping on the side (recipe below).", "In a bowl, mix 1 diced mango, 1 cup chopped cilantro, 2 tablespoons toasted sesame seeds, 2 tablespoons lemon juice, and a pinch of chili flakes. Serve with the chicken."}', 10);
